# Lint and deploy the necessary code to the server when pushing to the main branch
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  # Linting and unit testing job
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r requirements-dev.txt

      - name: Run flake8 linter
        run: flake8 . --exit-zero

      - name: Run unit tests
        run: python -m unittest discover

  # Deployment job
  deploy:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz -e "ssh -p ${{ secrets.PORT }}" \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.gitignore' \
            --exclude='readme.md' \
            --exclude='README.md' \
            --exclude='requirements-dev.txt' \
            ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:${{ secrets.PATH }}